### ISSUE TITLE
Useless error when cache key does not match

### ISSUE THREAD

**Issue by cg2v** [autolab/autolab-cli#23]
If the autolab cli's encryption key for the .arcache file does not match what was used to write it, all that's displayed is openssl's error (which is even less than useful because openssl's error strings are not loaded). The tool should either diagnose the mismatch and describe it, or proactively discard the cache

error:06065064:lib(6):func(101):reason(100):evp_enc.c:592:

**Comment by damianhxy** [comment]
Error on M1 Mac: `8127139840:error:06065064:digital envelope routines:EVP_DecryptFinal_ex:bad decrypt:crypto/evp/evp_enc.c:612:`

It doesn't seem meaningful to diagnose the mismatch, since according to openssl docs,
> Applications should not make control flow decisions based on specific error codes. Error codes are subject to change at any time (even in patch releases of OpenSSL). A particular error code can only be considered meaningful for control flow decisions if it is explicitly documented as such. New failure codes may still appear at any time.

It is probably better for `exit_with_crypto_error` to throw some kind of error that `load_tokens` or `store_tokens` can catch
